// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACTegVatNiZEwFNw36p1gC90atDJ3gA50',
    appId: '1:748610989842:web:f401aef1dbdb76aa000dcb',
    messagingSenderId: '748610989842',
    projectId: 'kasir-toti-2026-b6ce0',
    authDomain: 'kasir-toti-2026-b6ce0.firebaseapp.com',
    storageBucket: 'kasir-toti-2026-b6ce0.firebasestorage.app',
    measurementId: 'G-TNPETFPFMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADggdtmFhVwgqKRjula7gvzg8H0jH6zQ0',
    appId: '1:748610989842:android:f128ce37361785cf000dcb',
    messagingSenderId: '748610989842',
    projectId: 'kasir-toti-2026-b6ce0',
    storageBucket: 'kasir-toti-2026-b6ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8SS7iM_z_NNFEm-i8XQZw4lI3fcA1LKw',
    appId: '1:748610989842:ios:dbdb54bff19698b7000dcb',
    messagingSenderId: '748610989842',
    projectId: 'kasir-toti-2026-b6ce0',
    storageBucket: 'kasir-toti-2026-b6ce0.firebasestorage.app',
    iosBundleId: 'com.example.kasirPintarToti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8SS7iM_z_NNFEm-i8XQZw4lI3fcA1LKw',
    appId: '1:748610989842:ios:dbdb54bff19698b7000dcb',
    messagingSenderId: '748610989842',
    projectId: 'kasir-toti-2026-b6ce0',
    storageBucket: 'kasir-toti-2026-b6ce0.firebasestorage.app',
    iosBundleId: 'com.example.kasirPintarToti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACTegVatNiZEwFNw36p1gC90atDJ3gA50',
    appId: '1:748610989842:web:c87d164d5957ffd6000dcb',
    messagingSenderId: '748610989842',
    projectId: 'kasir-toti-2026-b6ce0',
    authDomain: 'kasir-toti-2026-b6ce0.firebaseapp.com',
    storageBucket: 'kasir-toti-2026-b6ce0.firebasestorage.app',
    measurementId: 'G-VCVK04668J',
  );
}
